
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace PredictiveMaintenanceModel_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            PredictiveMaintenanceModel.ModelInput sampleData = new PredictiveMaintenanceModel.ModelInput()
            {
                Product_ID = @"M14860",
                Type = @"M",
                Air_temperature = 298.1F,
                Process_temperature = 3048.6F,
                Rotational_speed = 155166F,
                Torque = 42.8F,
                Tool_wear = 9999F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = PredictiveMaintenanceModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Machine_failure with predicted Machine_failure from sample data...\n\n");


            Console.WriteLine($"Product_ID: {@"M14860"}");
            Console.WriteLine($"Type: {@"M"}");
            Console.WriteLine($"Air_temperature: {298.1F}");
            Console.WriteLine($"Process_temperature: {3048.6F}");
            Console.WriteLine($"Rotational_speed: {155166F}");
            Console.WriteLine($"Torque: {42.8F}");
            Console.WriteLine($"Tool_wear: {9999F}");
            Console.WriteLine($"Machine_failure: {0F}");


            Console.WriteLine($"\n\nPredicted Machine_failure: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
