﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MLModel1_ConsoleApp1
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"Type", @"Type")      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"UDI", @"UDI"),new InputOutputColumnPair(@"Air temperature [K]", @"Air temperature [K]"),new InputOutputColumnPair(@"Process temperature [K]", @"Process temperature [K]"),new InputOutputColumnPair(@"Rotational speed [rpm]", @"Rotational speed [rpm]"),new InputOutputColumnPair(@"Torque [Nm]", @"Torque [Nm]"),new InputOutputColumnPair(@"Tool wear [min]", @"Tool wear [min]")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Product ID", @"Product ID"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Type",@"UDI",@"Air temperature [K]",@"Process temperature [K]",@"Rotational speed [rpm]",@"Torque [Nm]",@"Tool wear [min]",@"Product ID"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"Machine failure", @"Machine failure"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastForest(new FastForestBinaryTrainer.Options(){NumberOfTrees=9,FeatureFraction=0.879156391336033F,LabelColumnName=@"Machine failure",FeatureColumnName=@"Features"}), labelColumnName: @"Machine failure"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
