
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                UDI = 1F,
                Product_ID = @"M14860",
                Type = @"M",
                Air_temperature__K_ = 298.1F,
                Process_temperature__K_ = 308.6F,
                Rotational_speed__rpm_ = 1551F,
                Torque__Nm_ = 42.8F,
                Tool_wear__min_ = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Machine_failure with predicted Machine_failure from sample data...\n\n");


            Console.WriteLine($"UDI: {1F}");
            Console.WriteLine($"Product_ID: {@"M14860"}");
            Console.WriteLine($"Type: {@"M"}");
            Console.WriteLine($"Air_temperature__K_: {298.1F}");
            Console.WriteLine($"Process_temperature__K_: {308.6F}");
            Console.WriteLine($"Rotational_speed__rpm_: {1551F}");
            Console.WriteLine($"Torque__Nm_: {42.8F}");
            Console.WriteLine($"Tool_wear__min_: {0F}");
            Console.WriteLine($"Machine_failure: {0F}");


            Console.WriteLine($"\n\nPredicted Machine_failure: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
